version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  ride-service:
    build: .
    container_name: ride-service
    ports:
      - "8000:8000"
    depends_on:
      - redis
